#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[246] =
    {   0,
        0,    0,   78,   76,   73,   77,   73,   74,   76,   76,
        1,   75,   69,   63,   69,   64,   69,   61,   66,   62,
       65,   69,   69,   69,   69,   69,    0,    0,   74,   74,
        3,    0,    0,    0,   35,    0,    0,    0,   54,   49,
        0,    0,   36,   56,    0,    1,   71,   69,   69,   69,
       58,   69,   69,   29,   69,   69,   69,   69,   59,   69,
       69,   69,   69,   69,   30,   69,   69,   14,   69,   69,
       69,   60,    0,    0,    0,    0,   70,    0,    0,    0,
        0,    0,    0,    0,   48,    0,   46,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   56,

       56,    2,   72,   72,   69,   69,   69,   24,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   25,   27,   13,   69,   69,   69,
       69,   69,   69,    0,    0,    3,   43,    0,    0,    0,
        0,   47,    0,    0,   45,    0,    0,    0,    0,    0,
       50,   44,   56,   56,   56,   56,   69,   69,   69,   26,
        5,   67,   69,   31,   68,   69,   69,   69,   69,   12,
       69,   69,   69,   69,   69,   69,   69,    4,   69,   69,
       57,    0,    0,    0,   51,    0,   55,    0,   41,   37,
       39,   38,   34,    0,   40,   56,   56,   56,   33,   22,

       32,    9,   15,   69,   28,   69,   69,   17,   19,   10,
        6,   69,   18,   20,   21,   69,    0,    0,    0,    0,
       53,   52,   56,   56,   16,    7,   23,    8,   69,    0,
        0,    0,   42,   56,   56,   11,    0,    0,   56,    0,
        0,   56,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,    1,    1,
       12,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   33,   34,   35,   36,   37,
        1,    1,    1,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   22,   49,   50,   51,   52,
       53,   54,   22,   55,   56,   57,   58,   59,   60,   61,
       62,   63,    1,   38,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    2,    3,    4,    1,    1,    5,    6,
        7,    1,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    2,    9,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8
    } ;

static const flex_int16_t yy_base[263] =
    {   0,
        0,    0,  298,  897,  897,  897,  281,  276,   53,    0,
       56,  897,   64,   76,  103,  101,  152,   65,   79,  102,
      109,  128,   80,  127,  149,  119,  123,  172,  275,  897,
       69,   54,   99,  130,  160,  127,  143,  156,  172,  162,
      178,  140,  168,  194,  264,   77,  262,  182,  202,  206,
      207,  208,  211,  212,  222,  214,  229,  233,  216,  237,
      245,  241,  285,  260,  238,  268,  283,  322,  263,  282,
      321,  267,  334,  337,  345,  314,  897,  346,  353,  256,
      191,  260,  339,  273,  897,  282,  897,  324,  331,  272,
      340,  339,  334,  357,  348,  350,  349,  368,    0,  372,

      396,  255,  231,  226,  355,  375,  376,  379,  380,  390,
      388,  397,  405,  399,  401,  410,  421,  431,  402,  444,
      422,  448,  455,  452,  423,  428,  457,  464,  477,  475,
      479,  478,  484,  516,  504,  218,  897,  415,  420,  442,
      480,  897,  484,  482,  897,  488,  517,  516,  513,  518,
      897,  897,  219,  527,  529,  531,  535,  538,  540,  541,
      544,  545,  547,  548,  554,  556,  558,  574,  567,  561,
      583,  594,  587,  603,  601,  596,  599,  562,  614,  604,
      897,  616,  658,  665,  897,  588,  897,  613,  897,  897,
      897,  897,  897,  625,  897,  643,  162,  649,  588,  644,

      645,  649,  655,  669,  668,  670,  674,  671,  675,  676,
      678,  700,  681,  685,  686,  690,   83,  722,  721,  604,
      897,  897,  689,  712,  695,  711,  726,  729,  730,  726,
      696,  738,  897,  137,  744,  735,  753,  769,  742,  746,
      775,  115,  748,  771,  897,  824,  832,   94,  837,  839,
      846,  852,  857,  859,  861,  864,  871,  877,   69,  882,
      888,   65
    } ;

static const flex_int16_t yy_def[263] =
    {   0,
      245,    1,  245,  245,  245,  245,  246,  247,  245,  248,
      249,  245,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  251,  252,  247,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  253,  245,  249,  254,  255,  250,  256,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  257,  257,  257,  258,  245,  258,  252,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  259,  248,  260,

      253,  245,  254,  254,  255,  256,  256,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  261,  258,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  259,  259,  259,  260,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      245,  262,  261,  261,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  259,  259,  259,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  262,  262,  262,  245,
      245,  245,  259,  259,  250,  250,  250,  250,  250,  262,
      262,  262,  245,  259,  259,  250,  262,  262,  259,  262,
      262,  259,  262,  262,    0,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245
    } ;

static const flex_int16_t yy_nxt[961] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,    4,   10,
       11,   12,   13,   14,   15,   13,   16,   17,   13,   13,
       13,   13,   18,   19,   20,   13,   13,   21,   22,   23,
       24,   25,   13,   26,   13,   13,   13,    4,    4,   13,
       14,   15,   13,   16,   17,   13,   13,   13,   18,   19,
       20,   13,   13,   21,   22,   23,   24,   25,   13,   26,
       13,   13,   13,   31,   45,   32,   46,   33,   34,   81,
       35,   36,  217,   37,   48,   48,  153,   80,   38,   31,
       39,   40,   41,   42,   43,   45,   48,   46,  181,   48,
       48,  182,   32,   51,   33,   34,   81,   35,   36,   69,

       37,   44,   50,   50,   38,   62,   39,   40,   41,   42,
       43,   48,   48,   48,   50,   52,   55,   50,   50,   48,
       51,   66,   53,   98,   63,   82,   69,   73,   64,   48,
       54,   62,   73,   74,   65,   56,   72,   48,   48,   50,
       50,   50,   52,   55,   67,   98,   83,   50,   66,   53,
       63,   82,   68,   70,   64,   86,   54,   50,   87,   48,
       65,   56,   48,   72,   57,   50,   50,   58,   88,   59,
       98,   67,   60,   83,   71,   95,   76,   77,   68,   70,
       84,   86,   78,   61,   89,   87,   96,   50,   91,   85,
       50,   57,   48,   92,   58,   88,   59,   97,   93,   60,

       71,   95,   98,   99,  100,   90,  137,   84,   94,   61,
       76,   89,   48,   96,   91,   85,  106,   48,   48,   92,
       50,   48,   48,   97,   48,   93,   48,   98,  136,  109,
      113,   90,   48,  137,   94,  110,  103,  111,  108,   48,
       50,  103,  112,   48,   50,   50,   50,   48,   48,   50,
       50,   48,   50,  115,   50,   48,  109,  113,  114,  118,
       50,  110,  116,  111,  108,  102,  136,   50,  117,  112,
       48,   50,  103,   48,  102,   50,   50,   48,   48,   50,
      115,   30,   30,   50,  114,  138,  118,  145,  116,  131,
       27,  123,   48,   48,  117,   48,  141,  245,   50,  124,

      119,   50,  120,  121,  245,   50,   50,  125,  126,  142,
      127,  138,  245,  132,  145,  131,  122,  123,   76,   77,
       50,   50,  141,   50,   78,  124,  245,  119,  245,  120,
      121,   48,   48,  125,  126,  142,  127,  128,   73,  132,
      129,   73,  122,   73,   74,  133,   73,   74,  143,   73,
       76,   77,   76,  130,   73,   74,   78,   76,   77,   50,
       50,  144,  139,   78,  128,   48,  146,  129,  140,  147,
      148,  133,  149,  245,  143,  150,  151,  152,  245,  130,
       98,   99,  100,  154,   76,  106,  106,  144,  139,   48,
       48,   76,  146,   50,  140,  147,  148,  155,   48,  149,

       48,  150,  151,  152,   98,   99,  100,   48,  157,   48,
      154,   48,   48,   50,   50,   48,  158,   50,   50,  161,
       48,  159,  168,  155,  245,  164,   50,  160,   50,  162,
      163,   48,   48,   48,  157,   50,  186,   50,   48,   50,
       50,   48,  158,   50,  165,  185,  161,  159,   50,  168,
      171,  166,  164,  160,   48,  162,  163,  167,   48,   50,
       50,   50,   48,  186,  169,   48,   50,   48,  245,   50,
      165,  185,  187,  170,   48,  245,  171,  172,  166,  245,
      173,  174,   50,  167,  175,   48,   50,   48,   48,   48,
       50,  169,  179,   50,   48,   50,  188,  245,  187,  170,

      189,  190,   50,  172,  177,  176,  173,  174,   76,   77,
      180,  175,  178,   50,   78,   50,   50,   50,  191,  179,
       73,  181,   50,  188,  182,   73,  183,  189,  190,  192,
      177,  176,  193,  194,  195,   98,  180,   98,  178,   98,
       99,  100,   76,  198,  191,   48,  245,  196,   48,  197,
       48,   48,  245,  200,   48,   48,  192,   48,   48,  193,
      194,  195,  199,  245,   48,  201,   48,  245,   48,  202,
      198,   48,   48,   50,  196,  197,   50,   48,   50,   50,
      200,  203,   50,   50,   48,   50,   50,  245,  199,  204,
      207,  201,   50,   48,   50,  202,   50,   48,   48,   50,

       50,  245,  205,  206,   48,   50,   48,  203,  245,   48,
      208,   48,   50,   48,   48,  204,  207,  210,  220,  211,
      233,   50,  209,  213,   48,   50,   50,  214,  205,  206,
      212,  218,   50,  215,   50,  216,  208,   50,  221,   50,
      245,   50,   50,  210,  220,  219,  211,  233,  209,  213,
      222,   98,   50,  214,   48,   48,  212,   98,  218,   48,
      215,  216,   73,  181,  221,   48,  182,   73,  183,   73,
      181,  219,  223,  182,   73,  183,  222,  224,   48,   48,
       48,   48,   50,   50,   48,   48,   48,   50,   48,  245,
      227,   48,  226,   50,  245,   48,   48,   98,  223,  225,

       48,  181,  245,  224,  182,   48,   50,   50,   50,   50,
       48,  234,   50,   50,   50,  229,   50,  227,  226,   50,
       98,   48,  228,   50,   50,  225,  181,  181,   50,  182,
      182,  181,  235,   50,  182,  232,   48,  234,   50,   48,
       48,  229,  230,  181,  231,   48,  182,  245,  228,   50,
       98,  181,   98,  181,  182,  237,  182,  245,  181,  235,
      236,  182,  232,  245,   50,  245,  238,   50,   50,  230,
      231,  239,  242,   50,  181,  240,  181,  182,  244,  182,
      181,  237,  245,  182,  245,  245,  236,  245,  245,  241,
      245,  245,  238,  245,  245,  245,  245,  239,  242,  245,

      245,  240,  243,  245,  244,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  241,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  243,   28,
      245,   28,   29,  245,   29,   29,   29,   29,   29,   29,
       29,   47,  245,   47,   47,   49,   49,   49,   75,  245,
      245,   75,   75,   75,   79,   79,  245,  245,   79,   79,
       79,  101,  101,  101,  101,  104,  104,  105,  105,  105,
      107,  107,  107,  134,  245,  245,  134,  134,  134,  135,
      135,  245,  245,  135,  135,  135,  156,  156,  156,  156,
      184,  184,  184,  184,  184,  184,    3,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245
    } ;

static const flex_int16_t yy_chk[961] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,   11,    9,   11,    9,    9,   32,
        9,    9,  262,    9,   13,   18,  259,   31,    9,   31,
        9,    9,    9,    9,    9,   46,   14,   46,  217,   19,
       23,  217,    9,   14,    9,    9,   32,    9,    9,   23,

        9,  248,   13,   18,    9,   19,    9,    9,    9,    9,
        9,   16,   20,   15,   14,   15,   16,   19,   23,   21,
       14,   21,   15,  242,   20,   33,   23,   27,   20,   26,
       15,   19,   27,   27,   20,   16,   26,   24,   22,   16,
       20,   15,   15,   16,   22,  234,   34,   21,   21,   15,
       20,   33,   22,   24,   20,   36,   15,   26,   37,   25,
       20,   16,   17,   26,   17,   24,   22,   17,   38,   17,
      197,   22,   17,   34,   25,   42,   28,   28,   22,   24,
       35,   36,   28,   17,   39,   37,   43,   25,   40,   35,
       17,   17,   48,   40,   17,   38,   17,   43,   41,   17,

       25,   42,   44,   44,   44,   39,   81,   35,   41,   17,
       28,   39,   49,   43,   40,   35,   50,   51,   52,   40,
       48,   53,   54,   43,   56,   41,   59,  153,  136,   53,
       56,   39,   55,   81,   41,   53,  104,   53,   52,   57,
       49,  103,   55,   58,   50,   51,   52,   60,   65,   53,
       54,   62,   56,   58,   59,   61,   53,   56,   57,   62,
       55,   53,   60,   53,   52,  102,   80,   57,   61,   55,
       64,   58,   47,   69,   45,   60,   65,   72,   66,   62,
       58,   29,    8,   61,   57,   82,   62,   90,   60,   69,
        7,   64,   70,   67,   61,   63,   84,    3,   64,   66,

       63,   69,   63,   63,    0,   72,   66,   67,   67,   86,
       67,   82,    0,   70,   90,   69,   63,   64,   76,   76,
       70,   67,   84,   63,   76,   66,    0,   63,    0,   63,
       63,   71,   68,   67,   67,   86,   67,   68,   73,   70,
       68,   74,   63,   73,   73,   71,   74,   74,   88,   75,
       78,   78,   76,   68,   75,   75,   78,   79,   79,   71,
       68,   89,   83,   79,   68,  105,   91,   68,   83,   92,
       93,   71,   94,    0,   88,   95,   96,   97,    0,   68,
      100,  100,  100,   98,   78,  106,  107,   89,   83,  108,
      109,   79,   91,  105,   83,   92,   93,   98,  111,   94,

      110,   95,   96,   97,  101,  101,  101,  112,  109,  114,
       98,  115,  119,  106,  107,  113,  110,  108,  109,  113,
      116,  111,  119,   98,    0,  116,  111,  112,  110,  114,
      115,  117,  121,  125,  109,  112,  139,  114,  126,  115,
      119,  118,  110,  113,  117,  138,  113,  111,  116,  119,
      121,  118,  116,  112,  120,  114,  115,  118,  122,  117,
      121,  125,  124,  139,  120,  123,  126,  127,    0,  118,
      117,  138,  140,  120,  128,    0,  121,  122,  118,    0,
      123,  124,  120,  118,  128,  130,  122,  129,  132,  131,
      124,  120,  132,  123,  133,  127,  141,    0,  140,  120,

      143,  144,  128,  122,  130,  129,  123,  124,  135,  135,
      133,  128,  131,  130,  135,  129,  132,  131,  146,  132,
      134,  134,  133,  141,  134,  134,  134,  143,  144,  147,
      130,  129,  148,  149,  150,  154,  133,  155,  131,  156,
      156,  156,  135,  155,  146,  157,    0,  154,  158,  154,
      159,  160,    0,  158,  161,  162,  147,  163,  164,  148,
      149,  150,  157,    0,  165,  159,  166,    0,  167,  163,
      155,  170,  178,  157,  154,  154,  158,  169,  159,  160,
      158,  166,  161,  162,  168,  163,  164,    0,  157,  167,
      169,  159,  165,  171,  166,  163,  167,  173,  199,  170,

      178,    0,  168,  168,  172,  169,  176,  166,    0,  177,
      171,  175,  168,  174,  180,  167,  169,  173,  186,  174,
      220,  171,  172,  176,  179,  173,  199,  177,  168,  168,
      175,  182,  172,  179,  176,  180,  171,  177,  188,  175,
        0,  174,  180,  173,  186,  182,  174,  220,  172,  176,
      194,  196,  179,  177,  200,  201,  175,  198,  182,  202,
      179,  180,  183,  183,  188,  203,  183,  183,  183,  184,
      184,  182,  196,  184,  184,  184,  194,  198,  205,  204,
      206,  208,  200,  201,  207,  209,  210,  202,  211,    0,
      207,  213,  206,  203,    0,  214,  215,  223,  196,  204,

      216,  231,    0,  198,  231,  225,  205,  204,  206,  208,
      212,  223,  207,  209,  210,  216,  211,  207,  206,  213,
      224,  226,  212,  214,  215,  204,  219,  218,  216,  219,
      218,  230,  224,  225,  230,  219,  227,  223,  212,  228,
      229,  216,  218,  232,  218,  236,  232,    0,  212,  226,
      239,  240,  235,  243,  240,  230,  243,    0,  237,  224,
      229,  237,  219,    0,  227,    0,  232,  228,  229,  218,
      218,  235,  239,  236,  238,  237,  244,  238,  243,  244,
      241,  230,    0,  241,    0,    0,  229,    0,    0,  238,
        0,    0,  232,    0,    0,    0,    0,  235,  239,    0,

        0,  237,  241,    0,  243,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  238,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  241,  246,
        0,  246,  247,    0,  247,  247,  247,  247,  247,  247,
      247,  249,    0,  249,  249,  250,  250,  250,  251,    0,
        0,  251,  251,  251,  252,  252,    0,    0,  252,  252,
      252,  253,  253,  253,  253,  254,  254,  255,  255,  255,
      256,  256,  256,  257,    0,    0,  257,  257,  257,  258,
      258,    0,    0,  258,  258,  258,  260,  260,  260,  260,
      261,  261,  261,  261,  261,  261,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 2 "flex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <iostream>
    #include "parser.h"

    using namespace std;
#line 749 "scanner.cpp"
#line 750 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 107 "flex.l"

#line 969 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 897 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 "flex.l"
{yylval.number = atoi(yytext); return number;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 109 "flex.l"
{yylval.number = atoi(yytext); return number;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 110 "flex.l"
{yylval.number = atoi(yytext); return number;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 112 "flex.l"
{return(show);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 113 "flex.l"
{return(readfile);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 114 "flex.l"
{return(pausa);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 115 "flex.l"
{return(mkdisk);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 116 "flex.l"
{return(rmdisk);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 117 "flex.l"
{return(fdisk);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 118 "flex.l"
{return(mount);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 119 "flex.l"
{return(unmount);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 120 "flex.l"
{return(mkfs);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 121 "flex.l"
{return(rep);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 122 "flex.l"
{return(rm);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 124 "flex.l"
{return(login);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 125 "flex.l"
{return(logout);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 126 "flex.l"
{return(mkgrp);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 127 "flex.l"
{return(rmgrp);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 128 "flex.l"
{return(mkusr);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 129 "flex.l"
{return(rmusr);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 130 "flex.l"
{return(touch);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "flex.l"
{return(chmod);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 133 "flex.l"
{return(mkfile);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 134 "flex.l"
{return(cat);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 135 "flex.l"
{return(rem);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 136 "flex.l"
{return(edit);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 137 "flex.l"
{return(ren);} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 138 "flex.l"
{return(mkdir);} 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 139 "flex.l"
{return(cp);} 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 140 "flex.l"
{return(mv);} 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 141 "flex.l"
{return(findd);} 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 142 "flex.l"
{return(chownn);} 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 143 "flex.l"
{return(chgrp);} 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 145 "flex.l"
{return(size);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 146 "flex.l"
{return(fit);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 147 "flex.l"
{return(units);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 148 "flex.l"
{return(path);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 149 "flex.l"
{return(ruta);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 150 "flex.l"
{return(root);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 151 "flex.l"
{return(type);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 152 "flex.l"
{return(name);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 153 "flex.l"
{return(delet);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 154 "flex.l"
{return(add);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 155 "flex.l"
{return(usr);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 156 "flex.l"
{return(pass);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 157 "flex.l"
{return(id);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 158 "flex.l"
{return(grp);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 159 "flex.l"
{return(fs);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 160 "flex.l"
{return(recursive);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 161 "flex.l"
{return(ugo);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 162 "flex.l"
{return(cont);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 163 "flex.l"
{return(stdinn);} 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 164 "flex.l"
{return(filen);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 165 "flex.l"
{return(pp);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 166 "flex.l"
{return(dest);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 168 "flex.l"
{strcpy(yylval.text, yytext); return(e_path);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 169 "flex.l"
{strcpy(yylval.text, yytext); return(e_path);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 170 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_fit);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 171 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_fit);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 172 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_fit);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 173 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_units);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 174 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_units);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 175 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_units);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 176 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_type);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 177 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_type);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 178 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_type);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 179 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_delet);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 180 "flex.l"
{sscanf(yytext, "%s", yylval.entrance); return(e_delet);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 181 "flex.l"
{strcpy(yylval.text, yytext); return(e_name);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 182 "flex.l"
{strcpy(yylval.text, yytext); return(e_name);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 183 "flex.l"
{strcpy(yylval.text, yytext); return(e_id);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 184 "flex.l"
{strcpy(yylval.text, yytext); return(password);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 186 "flex.l"
{}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 187 "flex.l"
{strcpy(yylval.text, yytext); return(comentario);}// creo que este lo voy a tener que poner como delimitador porque el comentario no hace nada
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 188 "flex.l"
{return(igual);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 189 "flex.l"
{printf("Caracter %s no admitido\n ", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 191 "flex.l"
ECHO;
	YY_BREAK
#line 1411 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 245);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 191 "flex.l"

